### ISSUE TITLE
not compatible with python3

### ISSUE THREAD

**Issue by jose1711** [dezhin/osmread#4]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/osmread/**init**.py", line 25, in parse_file
    for e in parser.parse_file(filename):
  File "/usr/lib/python3.5/site-packages/osmread/parser/**init**.py", line 18, in parse_file
    for e in self.parse(fp):
  File "/usr/lib/python3.5/site-packages/osmread/parser/xml.py", line 39, in parse
    _id = int(attrs['id'])
NameError: name 'long' is not defined

**Comment by Advil-Robin** [comment]
Same,

it's not compatible with python3,
my error:

File "C:\Users\Robin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\osmread\parser\pbf.py", line 113
    try:
      ^
SyntaxError: invalid syntax

**Comment by mattvend** [comment]
Same issue here on OSX.

/usr/local/lib/python3.5/site-packages/osmread/parser/xml.py in parse(self, fp)
     37                 attrs = elem.attrib
     38                 if elem.tag in ('node', 'way', 'relation'):
---> 39                     _id = long(attrs['id'])
     40                     _version = int(attrs['version'])
     41                     _changeset = int(attrs['changeset'])

NameError: name 'long' is not defined

**Comment by dezhin** [comment]
Just published updated version to PyPi. Please update! It should fix this issue.
